// <auto-generated />
namespace PAEDUCA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ActualizacionconobjetosdeMartin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActualizacionconobjetosdeMartin));
        
        string IMigrationMetadata.Id
        {
            get { return "201902141919254_Actualizacion con objetos de Martin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
